//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginsCurse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public Nullable<int> SiteNameId { get; set; }
        public string Description { get; set; }
        public string Login1 { get; set; }
        public string Password { get; set; }
        public bool IsEncrypted { get; set; }
    
        public virtual SitesAddress SitesAddress { get; set; }
        public virtual SitesName SitesName { get; set; }
    }
}
